# Generated by Django 5.0.1 on 2025-06-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=50)),
                ('population', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cases', models.FloatField(blank=True, null=True)),
                ('new_cases', models.FloatField(blank=True, null=True)),
                ('new_cases_smoothed', models.FloatField(blank=True, null=True)),
                ('total_deaths', models.FloatField(blank=True, null=True)),
                ('new_deaths', models.FloatField(blank=True, null=True)),
                ('new_deaths_smoothed', models.FloatField(blank=True, null=True)),
                ('total_vaccinations', models.FloatField(blank=True, null=True)),
                ('people_vaccinated', models.FloatField(blank=True, null=True)),
                ('people_fully_vaccinated', models.FloatField(blank=True, null=True)),
                ('new_vaccinations', models.FloatField(blank=True, null=True)),
                ('new_vaccinations_smoothed', models.FloatField(blank=True, null=True)),
                ('reproduction_rate', models.FloatField(blank=True, null=True)),
                ('icu_patients', models.FloatField(blank=True, null=True)),
                ('hosp_patients', models.FloatField(blank=True, null=True)),
                ('positive_rate', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid_data', to='data.country')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('country', 'date')},
            },
        ),
    ]
